// components/Sidebar.tsx
import { useState, useEffect } from 'react';

export default function NexusSidebar({ userProfile }) {
  const [copied, setCopied] = useState(false);

  // Generate the full referral link
  const referralLink = `${window.location.origin}/signup?ref=${userProfile.referral_code}`;

  const copyLink = () => {
    navigator.clipboard.writeText(referralLink);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-64 bg-black border-r border-emerald-500/20 p-4 flex flex-col h-screen font-mono">
      {/* 🏛️ PRESTIGE PANEL */}
      <div className="mb-8 p-3 border border-emerald-500/40 bg-emerald-500/5 rounded">
        <h3 className="text-[10px] text-emerald-500/60 uppercase tracking-widest">Permanent_Prestige</h3>
        <p className="text-2xl font-black text-white">{userProfile.prestige_score.toLocaleString()}</p>
        <div className="h-1 bg-zinc-800 mt-2 rounded-full overflow-hidden">
          <div className="h-full bg-emerald-500" style={{ width: '65%' }}></div>
        </div>
      </div>

      {/* 🔗 RECRUITMENT LINK (Phase 1 Growth) */}
      <div className="mb-8">
        <h3 className="text-[10px] text-emerald-500/60 uppercase mb-2 tracking-widest">Recruitment_Link</h3>
        <button 
          onClick={copyLink}
          className="w-full bg-zinc-900 border border-emerald-500/30 p-2 text-[11px] text-emerald-400 hover:bg-emerald-500 hover:text-black transition-all truncate"
        >
          {copied ? "COPIED_TO_CLIPBOARD" : userProfile.referral_code.toUpperCase()}
        </button>
        <p className="text-[9px] text-zinc-500 mt-2 leading-tight">
          Earn 25% of all Signal generated by units recruited via this link.
        </p>
      </div>

      {/* 🛰️ SEASON COUNTDOWN */}
      <div className="mt-auto pt-4 border-t border-emerald-500/10">
        <div className="flex justify-between items-center text-[10px]">
          <span className="text-zinc-500">SEASON_01_RESET</span>
          <span className="text-orange-500 animate-pulse">14H : 22M : 05S</span>
        </div>
      </div>
    </div>
  );
}